/* eslint-disable */
/**
 * Generated by hand to match `npx convex codegen` output. `npx convex dev` regenerates this file.
 * @module
 */

import { anyApi, componentsGeneric } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
