/* eslint-disable */
/**
 * Generated by hand to match `npx convex codegen` output. `npx convex dev` regenerates this file.
 * @module
 */

import type * as auth from "../auth.js";
import type * as categorize from "../categorize.js";
import type * as http from "../http.js";
import type * as imports from "../imports.js";
import type * as rows from "../rows.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  categorize: typeof categorize;
  http: typeof http;
  imports: typeof imports;
  rows: typeof rows;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
export declare const components: {};
