/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IncomesRouteImport } from './routes/incomes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InvestmentsIndexRouteImport } from './routes/investments.index'
import { Route as InvestmentsIdRouteImport } from './routes/investments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomesRoute = IncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIdRoute = InvestmentsIdRouteImport.update({
  id: '/investments/$id',
  path: '/investments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/investments/$id': typeof InvestmentsIdRoute
  '/investments/': typeof InvestmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/investments/$id': typeof InvestmentsIdRoute
  '/investments': typeof InvestmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/investments/$id': typeof InvestmentsIdRoute
  '/investments/': typeof InvestmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/investments/$id'
    | '/investments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/investments/$id'
    | '/investments'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/investments/$id'
    | '/investments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomesRoute: typeof IncomesRoute
  SettingsRoute: typeof SettingsRoute
  InvestmentsIdRoute: typeof InvestmentsIdRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/$id': {
      id: '/investments/$id'
      path: '/investments/$id'
      fullPath: '/investments/$id'
      preLoaderRoute: typeof InvestmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomesRoute: IncomesRoute,
  SettingsRoute: SettingsRoute,
  InvestmentsIdRoute: InvestmentsIdRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
