/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IncomesRouteImport } from './routes/incomes'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentsIndexRouteImport } from './routes/investments.index'
import { Route as InvestmentsNewRouteImport } from './routes/investments.new'
import { Route as InvestmentsIdRouteImport } from './routes/investments.$id'
import { Route as ApiCompletionRouteImport } from './routes/api/completion'
import { Route as InvestmentsIdEditRouteImport } from './routes/investments.$id.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomesRoute = IncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsNewRoute = InvestmentsNewRouteImport.update({
  id: '/investments/new',
  path: '/investments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIdRoute = InvestmentsIdRouteImport.update({
  id: '/investments/$id',
  path: '/investments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompletionRoute = ApiCompletionRouteImport.update({
  id: '/api/completion',
  path: '/api/completion',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIdEditRoute = InvestmentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvestmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/api/completion': typeof ApiCompletionRoute
  '/investments/$id': typeof InvestmentsIdRouteWithChildren
  '/investments/new': typeof InvestmentsNewRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/investments/$id/edit': typeof InvestmentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/api/completion': typeof ApiCompletionRoute
  '/investments/$id': typeof InvestmentsIdRouteWithChildren
  '/investments/new': typeof InvestmentsNewRoute
  '/investments': typeof InvestmentsIndexRoute
  '/investments/$id/edit': typeof InvestmentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/settings': typeof SettingsRoute
  '/api/completion': typeof ApiCompletionRoute
  '/investments/$id': typeof InvestmentsIdRouteWithChildren
  '/investments/new': typeof InvestmentsNewRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/investments/$id/edit': typeof InvestmentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/api/completion'
    | '/investments/$id'
    | '/investments/new'
    | '/investments/'
    | '/investments/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/api/completion'
    | '/investments/$id'
    | '/investments/new'
    | '/investments'
    | '/investments/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/expenses'
    | '/incomes'
    | '/settings'
    | '/api/completion'
    | '/investments/$id'
    | '/investments/new'
    | '/investments/'
    | '/investments/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomesRoute: typeof IncomesRoute
  SettingsRoute: typeof SettingsRoute
  ApiCompletionRoute: typeof ApiCompletionRoute
  InvestmentsIdRoute: typeof InvestmentsIdRouteWithChildren
  InvestmentsNewRoute: typeof InvestmentsNewRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/new': {
      id: '/investments/new'
      path: '/investments/new'
      fullPath: '/investments/new'
      preLoaderRoute: typeof InvestmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/$id': {
      id: '/investments/$id'
      path: '/investments/$id'
      fullPath: '/investments/$id'
      preLoaderRoute: typeof InvestmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/completion': {
      id: '/api/completion'
      path: '/api/completion'
      fullPath: '/api/completion'
      preLoaderRoute: typeof ApiCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/$id/edit': {
      id: '/investments/$id/edit'
      path: '/edit'
      fullPath: '/investments/$id/edit'
      preLoaderRoute: typeof InvestmentsIdEditRouteImport
      parentRoute: typeof InvestmentsIdRoute
    }
  }
}

interface InvestmentsIdRouteChildren {
  InvestmentsIdEditRoute: typeof InvestmentsIdEditRoute
}

const InvestmentsIdRouteChildren: InvestmentsIdRouteChildren = {
  InvestmentsIdEditRoute: InvestmentsIdEditRoute,
}

const InvestmentsIdRouteWithChildren = InvestmentsIdRoute._addFileChildren(
  InvestmentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomesRoute: IncomesRoute,
  SettingsRoute: SettingsRoute,
  ApiCompletionRoute: ApiCompletionRoute,
  InvestmentsIdRoute: InvestmentsIdRouteWithChildren,
  InvestmentsNewRoute: InvestmentsNewRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
